#!/usr/bin/python3
"""2fa - print the current TOTP code of every account in .secrets.json

Usage: 2fa        (from $HOME)

.secrets.json maps a label to a base32 secret; install-dotfiles links it into $HOME
from secrets/config/googleauth.json.
"""

import hmac, base64, struct, hashlib, time, json, sys

def get_hotp_token(secret, intervals_no):
  secret = secret.replace(' ', '')
  if len(secret) % 8: secret += '=' * (8 - len(secret) % 8)
  key = base64.b32decode(secret, True)
  msg = struct.pack(">Q", intervals_no)
  h = hmac.new(key, msg, hashlib.sha1).digest()
  o = h[19] & 15
  h = str((struct.unpack(">I", h[o:o+4])[0] & 0x7fffffff) % 1000000)
  return '{:06}'.format(int(h))


def get_totp_token(secret):
  return get_hotp_token(secret, int(time.time()) // 30)

def main():
  if sys.argv[1:2] in (['-h'], ['--help']):
    print(__doc__.strip()); return
  with open('.secrets.json', 'r') as f: secrets = json.load(f)

  for label, key in sorted(secrets.items()):
    print('{}: {}'.format(label, get_totp_token(key)))


if __name__ == "__main__":
  main()
