#!/usr/bin/env bash

set -eo pipefail

REPO="$1"
if [ -z "$REPO" ]; then
  echo "Usage: $0 <path-to-repo>"
  exit 1
fi

devcontainer up \
  --mount type=bind,source=/chome/santini/dhevmera,target=/dhevmera \
  --mount type=bind,source=/chome/santini/secrets,target=/secrets \
  --mount type=bind,source=/usr/local/bin/code,target=/code \
  --workspace-folder "$REPO"

#  --dotfiles-repository https://github.com/mapio/dhevmera \
#  --dotfiles-install-command ./scripts/setup \
