#!/usr/bin/env bash

set -euo pipefail

REPO="$1"
if [ -z "$REPO" ]; then
  echo "Usage: $0 <path-to-repo>"
  exit 1
fi

devcontainer up \
  --dotfiles-repository https://github.com/mapio/dhevmera \
  --dotfiles-install-command ./scripts/setup \
  --mount type=bind,source=/home/santini/dhevmera,target=/dhevmera \
  --workspace-folder "$REPO"
