#!/usr/bin/env bash

set -euo pipefail

SERVER_TYPE="${SERVER_TYPE:-cx33}"
SERVER_NAME="${SERVER_NAME:-dhevmera}"

# Define helper function for output

if [ -t 1 ]; then
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  YELLOW='\033[0;33m'
  BLUE='\033[0;34m'
  BOLD='\033[1m'
  RESET='\033[0m'
else
  RED=''; GREEN=''; YELLOW=''; BLUE=''; BOLD=''; RESET=''
fi

log()      { printf "\n%b\n\n" "${BLUE}${BOLD}==> $*${RESET}"; }
ok()       { printf "%b\n" "${GREEN}✔ $*${RESET}"; }
warn()     { printf "%b\n" "${YELLOW}⚠ $*${RESET}"; }
die()      { printf "%b\n" "${RED}✖ $*${RESET}" >&2; exit 1; }

## Create server

log "Creating server '$SERVER_NAME', type '$SERVER_TYPE'..."

hcloud server create \
  --name "$SERVER_NAME" \
  --type "$SERVER_TYPE" \
  --image ubuntu-24.04 \
  --firewall ssh-wireguard \
  --user-data-from-file ./cloud/cloud-init.yaml

ok "Server created."

## Wait for server to be reachable

SERVER_IP="$(hcloud server ip "$SERVER_NAME")"

log "Waiting for server at $SERVER_IP to become reachable on ssh port and have the dhevmera directory..."

for delay in 1 1 2 3 5 8 13 21; do
  if nc -z -w2 "$SERVER_IP" 22; then
    ok "Server is reachable at $SERVER_IP."
    break
  fi
  sleep "$delay"
done

for delay in 1 1 2 3 5 8 13 21; do
  if ssh "$SERVER_IP" test -d dhevmera; then
    ok "Server has the dhevmera directory."
    break
  fi
  sleep "$delay"
done

## Deploy secrets

log "Deploying secrets script to server..."

scp ./scripts/unpack-secrets "$SERVER_IP":dhevmera/scripts/unpack-secrets

ok "Secrets script deployed."

## Unpack secrets on server

log "Unpacking secrets on server..."
ssh -t "$SERVER_IP" ./dhevmera/scripts/unpack-secrets

## Wait for cloud-init to complete

log "Waiting for cloud-init to complete on server..."
ssh "$SERVER_IP" -- cloud-init status --wait

ok "Cloud-init completed on server."