#!/usr/bin/env bash

set -eo pipefail

# Keep a log of the setup process

LOGFILE="$HOME/.install-software.log"
exec 3>&1
exec > >(tee -a "$LOGFILE") 2>&1

# Determine if we have sudo or are root

if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
elif command -v sudo >/dev/null 2>&1; then
  SUDO="sudo"
else
  echo "ERROR: need root privileges but sudo is not installed (and you are not root)." >&2
  exit 1
fi

# Define helper function and vars 

if [ -t 3 ]; then
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  YELLOW='\033[0;33m'
  BLUE='\033[0;34m'
  BOLD='\033[1m'
  RESET='\033[0m'
else
  RED=''; GREEN=''; YELLOW=''; BLUE=''; BOLD=''; RESET=''
fi

log()      { printf "\n%b\n\n" "${BLUE}${BOLD}==> $*${RESET}"; }
ok()       { printf "\n%b\n\n" "${GREEN}✔ $*${RESET}"; }
warn()     { printf "\n%b\n\n" "${YELLOW}⚠ $*${RESET}"; }
die()      { printf "\n%b\n\n" "${RED}✖ $*${RESET}" >&2; exit 1; }

ver_ge() {  # ver_ge A B  -> true if A >= B (semver-ish, numeric)
  python3 - <<'EOF' "$1" "$2"
import sys
from packaging.version import Version
a,b = sys.argv[1], sys.argv[2]
print(int(Version(a) >= Version(b)))
EOF
}

NODE_MAJOR=24
DOCKER_MAJOR=29
ARCH=$(dpkg --print-architecture)
. /etc/os-release

# Fix timezone to avoid tzdata prompts

export DEBIAN_FRONTEND=noninteractive
export TZ=Europe/Rome

$SUDO ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime
echo "$TZ" | $SUDO tee /etc/timezone > /dev/null

# Update and install system software

log "Updating package lists and installing prerequisites..."
$SUDO apt-get update -y
$SUDO apt-get install -y --no-install-recommends tzdata
$SUDO dpkg-reconfigure -f noninteractive tzdata
$SUDO apt-get upgrade -y
$SUDO apt-get install -y ca-certificates curl direnv git gnupg hcloud-cli jq ncdu python3-packaging python3-pip python3-venv restic zip zfsutils-linux

## Update or install additional software

for script in ./scripts/install.d/*.sh; do

  filename=$(basename "$script")
  name=${filename#??-}
  name=${name%.sh}

  log "Running: $name"

  source "$script"
  status=$?

  if [ $status -ne 0 ]; then
    log "ERROR: $name failed with exit code $status"
  fi
done

# Done!

ok "OS setup completed successfully!"
touch "$HOME/.install-software.complete"
