#!/usr/bin/env bash

set -eo pipefail

SRC_DIR="./secrets"
DST_SCRIPT="./scripts/unpack-secrets"

if [ ! -d $SRC_DIR ]; then
  echo "No $SRC_DIR directory found, nothing to pack."
  exit 1
fi

if [ -f $DST_SCRIPT ]; then
  echo "$DST_SCRIPT already exists, please remove it before packing again."
  exit 1
fi

cat > $DST_SCRIPT <<'SCRIPT'
#!/usr/bin/env bash
set -eo pipefail

SECRETS_DIR="${1:-/chome/santini/dhevmera}"

if [[ -d "$SECRETS_DIR/secrets" ]]; then
  echo "The directory '$SECRETS_DIR/secrets' directory already exists, nothing to do."
  exit 0
fi

mkdir -p "$SECRETS_DIR"

read -r -s -p "Enter the secrets passphrase: " pw </dev/tty && printf '\n' >/dev/tty
gpg --decrypt --pinentry-mode loopback --passphrase-fd 3 3<<<"$pw" <<'EOF' | tar xvf - -C "$SECRETS_DIR"
SCRIPT

tar cf - $SRC_DIR \
  | gpg >> $DST_SCRIPT \
    --symmetric --armor \
    --cipher-algo AES256 \
    --s2k-digest-algo SHA512 \
    --s2k-mode 3 \
    --s2k-count 65011712 \
    --force-aead --aead-algo OCB \
    --compress-algo none  

cat >> $DST_SCRIPT <<'SCRIPT'
EOF

echo "Secrets decrypted into $SECRETS_DIR/secrets"
chmod -R 700 "$SECRETS_DIR/secrets"

touch $HOME/.unpack-secrets.complete

SCRIPT

chmod 700 $DST_SCRIPT



