#!/usr/bin/env bash

set -euo pipefail

source $HOME/.bash_secrets

if [ ! -v TAILSCALE_AUTH_KEY ]; then
  echo "Missing Tailscale auth key"
  exit 1
fi

sudo tailscale up --authkey "$TAILSCALE_AUTH_KEY" --hostname dhevmera --ssh --operator santini
