#!/usr/bin/env bash

set -eo pipefail

VSCODE_DIR="${1:-/chome/santini/vscode}"

if [ ! -d "$VSCODE_DIR" ]; then
  echo "Missing VSCode directory at $VSCODE_DIR"
  exit 1
fi

nohup code --cli-data-dir "$VSCODE_DIR/cli-data-dir" serve-web --server-data-dir "$VSCODE_DIR/server-data-dir" --connection-token "$VSCODE_TOKEN" > "$VSCODE_DIR/vscode.log" 2>&1 &
tailscale funnel --bg 8000
